import type {
    IIndexQuote,
    ILadderLevel,
    IMarketEvent,
    IMarketMetric,
    IMarketTab,
    ISectorHeat,
    IStockQuote,
} from "@/features/market-dashboard/market-types";

export const marketTabs: IMarketTab[] = [
    { id: "overview", label: "市场总览" },
    { id: "sectors", label: "板块轮动" },
    { id: "themes", label: "热点题材" },
    { id: "ladder", label: "涨停阶梯" },
    { id: "leaders", label: "龙头观察" },
    { id: "radar", label: "异动雷达", count: 67 },
    { id: "multi", label: "多股同屏" },
    { id: "review", label: "盘后复盘" },
];

export const indexQuotes: IIndexQuote[] = [
    { label: "综合等权", value: "1,060.36", change: "+6.04%", points: [2, 6, 8, 7, 7, 8, 8] },
    { label: "主板样本", value: "1,030.05", change: "+3.01%", points: [3, 8, 6, 4, 5, 7, 8] },
    { label: "创业板样本", value: "1,061.67", change: "+6.17%", points: [2, 3, 4, 5, 6, 6, 7] },
    { label: "科创板样本", value: "1,051.57", change: "+5.16%", points: [2, 6, 7, 7, 6, 4, 3] },
    { label: "北交所样本", value: "1,191.81", change: "+19.18%", points: [2, 5, 7, 7, 6, 6, 7] },
    { label: "核心观察", value: "1,063.12", change: "+6.31%", points: [2, 7, 6, 4, 4, 5, 6] },
];

export const marketMetrics: IMarketMetric[] = [
    { label: "上涨 / 下跌", value: "31", suffix: "/ 14", detail: "0 平盘 · 45/47 有效", tone: "muted" },
    { label: "当前封板", value: "14", detail: "触板 18 · 不限价格的不参与", tone: "up" },
    { label: "炸板未回封", value: "4", detail: "炸板率 22.22% · 点击看分母", tone: "amber" },
    { label: "当前跌停", value: "4", detail: "以规则跌停价作判断", tone: "positive" },
    { label: "市场高度", value: "7", suffix: "板", detail: "盘中暂定 · 非收盘连板", tone: "muted" },
    { label: "样本成交额", value: "103.70亿", suffix: "元", detail: "较前样本日同时 +15.61%", tone: "muted" },
];

export const sectorHeat: ISectorHeat[] = [
    { name: "人形机器人", change: "+7.24%", detail: "3 封板 · 5.45亿元" },
    { name: "低空经济", change: "+7.10%", detail: "3 封板 · 24.47亿元" },
    { name: "电网设备", change: "+6.88%", detail: "3 封板 · 12.94亿元" },
    { name: "商业航天", change: "+4.75%", detail: "3 封板 · 7.08亿元" },
    { name: "有色金属", change: "+4.31%", detail: "扩散 83% · 9.62亿元" },
    { name: "算力基础设施", change: "+3.76%", detail: "2 封板 · 18.11亿元" },
    { name: "创新药", change: "+3.34%", detail: "2 封板 · 8.26亿元" },
    { name: "半导体", change: "+3.11%", detail: "扩散 67% · 13.72亿元" },
];

export const marketEvents: IMarketEvent[] = [
    { time: "14:13", category: "首次封板", name: "星锐精工", detail: "人形机器人 · 关注事件" },
    { time: "14:13", category: "首次封板", name: "川岳变压", detail: "电网设备 · 关注事件" },
    { time: "14:13", category: "首次封板", name: "凌云智航", detail: "低空经济 · 关注事件" },
    { time: "14:13", category: "首次封板", name: "青源桥材", detail: "有色金属 · 关注事件" },
    { time: "13:27", category: "回封", name: "新澜医药", detail: "创新药 · 关注事件" },
    { time: "13:01", category: "回封", name: "飞衡通信", detail: "商业航天 · 关注事件" },
];

export const stockQuotes: IStockQuote[] = [
    {
        name: "云启算力",
        code: "SIM001",
        board: "主板",
        price: "16.81",
        change: "+10.01%",
        amount: "4,425.38万元",
        turnover: "11.02%",
        status: "7连板·暂",
        firstSeal: "10:04",
        openCount: 0,
        streak: 7,
    },
    {
        name: "微澜光科",
        code: "SIM037",
        board: "主板",
        price: "54.43",
        change: "+10.00%",
        amount: "6.06亿元",
        turnover: "8.51%",
        status: "4连板·暂",
        firstSeal: "10:00",
        openCount: 1,
        streak: 4,
    },
    {
        name: "飞衡通信",
        code: "SIM013",
        board: "主板",
        price: "26.90",
        change: "+10.02%",
        amount: "1.36亿元",
        turnover: "8.56%",
        status: "4连板·暂",
        firstSeal: "10:30",
        openCount: 1,
        streak: 4,
    },
    {
        name: "新澜医药",
        code: "SIM025",
        board: "主板",
        price: "40.89",
        change: "+10.01%",
        amount: "3.05亿元",
        turnover: "7.91%",
        status: "4连板·暂",
        firstSeal: "10:56",
        openCount: 1,
        streak: 4,
    },
    {
        name: "青岚飞控",
        code: "SIM036",
        board: "北交所",
        price: "61.50",
        change: "+29.99%",
        amount: "7.33亿元",
        turnover: "9.32%",
        status: "2连板·暂",
        firstSeal: "09:51",
        openCount: 0,
        streak: 2,
    },
    {
        name: "安行机器人",
        code: "SIM012",
        board: "北交所",
        price: "30.34",
        change: "+29.99%",
        amount: "1.47亿元",
        turnover: "8.67%",
        status: "2连板·暂",
        firstSeal: "10:21",
        openCount: 0,
        streak: 2,
    },
    {
        name: "衡达电缆",
        code: "SIM024",
        board: "北交所",
        price: "44.60",
        change: "+29.99%",
        amount: "3.28亿元",
        turnover: "8.15%",
        status: "2连板·暂",
        firstSeal: "10:47",
        openCount: 0,
        streak: 2,
    },
    {
        name: "启航视觉",
        code: "SIM011",
        board: "科创板",
        price: "40.24",
        change: "+20.01%",
        amount: "1.96亿元",
        turnover: "9.13%",
        status: "首板·暂",
        firstSeal: "10:12",
        openCount: 0,
        streak: 1,
    },
    {
        name: "清源储能",
        code: "SIM023",
        board: "科创板",
        price: "50.87",
        change: "+20.00%",
        amount: "3.69亿元",
        turnover: "8.22%",
        status: "首板·暂",
        firstSeal: "10:38",
        openCount: 0,
        streak: 1,
    },
    {
        name: "天衡空管",
        code: "SIM035",
        board: "科创板",
        price: "50.98",
        change: "+20.01%",
        amount: "5.10亿元",
        turnover: "8.14%",
        status: "首板·暂",
        firstSeal: "11:04",
        openCount: 0,
        streak: 1,
    },
    {
        name: "星锐精工",
        code: "SIM009",
        board: "主板",
        price: "16.14",
        change: "+10.02%",
        amount: "5,494.87万元",
        turnover: "7.33%",
        status: "首板·暂",
        firstSeal: "14:13",
        openCount: 0,
        streak: 1,
    },
    {
        name: "川岳变压",
        code: "SIM021",
        board: "主板",
        price: "26.97",
        change: "+9.99%",
        amount: "1.53亿元",
        turnover: "7.03%",
        status: "首板·暂",
        firstSeal: "14:13",
        openCount: 0,
        streak: 1,
    },
    {
        name: "凌云智航",
        code: "SIM033",
        board: "主板",
        price: "36.59",
        change: "+10.01%",
        amount: "2.81亿元",
        turnover: "6.62%",
        status: "首板·暂",
        firstSeal: "14:13",
        openCount: 0,
        streak: 1,
    },
    {
        name: "青源桥材",
        code: "SIM045",
        board: "主板",
        price: "48.66",
        change: "+9.99%",
        amount: "5.06亿元",
        turnover: "6.90%",
        status: "首板·暂",
        firstSeal: "14:13",
        openCount: 0,
        streak: 1,
    },
];

const ladderTheme = ["算力基础设施", "低空经济", "创新药", "电网设备", "人形机器人", "有色金属"];

export const ladderLevels: ILadderLevel[] = [6, 5, 4, 3, 2, 1].map((level) => ({
    level,
    label: level === 6 ? "6+" : level === 1 ? "首" : String(level),
    stocks: stockQuotes
        .filter((stock) => (level === 6 ? stock.streak >= 6 : stock.streak === level))
        .map((stock, index) => ({
            board: stock.board,
            change: stock.change,
            name: stock.name,
            streak: stock.streak,
            theme: ladderTheme[(stock.streak + index) % ladderTheme.length] ?? "综合题材",
        })),
}));

export const chartSeries = [0.5, 2.1, 3.6, 4.8, 5.4, 5.7, 5.6, 5.55, 5.52, 5.62, 5.72, 5.95, 6.18];

export const breadthBuckets = [
    { label: "≤ -7%", value: 8, tone: "down" },
    { label: "-7 ~ -3%", value: 0, tone: "down" },
    { label: "-3 ~ 0%", value: 6, tone: "down" },
    { label: "平盘", value: 0, tone: "flat" },
    { label: "0 ~ 3%", value: 5, tone: "up" },
    { label: "3 ~ 7%", value: 2, tone: "up" },
    { label: "≥ 7%", value: 24, tone: "up" },
] as const;
