export interface ITopologyGate {
    id: string;
    question: string;
    detail: string;
    source: string;
    yes: string;
    no: string;
    yesNext?: string;
    noNext?: string;
    row?: number;
}

export interface ITopologyFlow {
    id: string;
    label: string;
    description: string;
    mode: "gates" | "exits";
    gates: readonly ITopologyGate[];
    completion: string;
}

/**
 * 每个判断都显式给出两条出口。源码变更由 topology-data.test.ts
 * 的指纹门禁提醒维护者同步复核这里的条件和路径。
 */
export const topologyFlows: readonly [ITopologyFlow, ...ITopologyFlow[]] = [
    {
        id: "structure",
        label: "① 结构与候选",
        description: "常规 N 买点只使用截至当前交易日已确认的结构；V3 浅回撤横盘突破与组合 A 回调突破另走独立通道。",
        mode: "gates",
        completion: "进入买点分类与入场确认",
        gates: [
            {
                id: "history",
                question: "日线输入有效且日期唯一？",
                detail: "空输入直接返回；重复交易日期拒绝计算。历史截面只看截至当前日的数据。",
                source: "integrated_strategy.py · generate_system_signals:159–176",
                yes: "逐日观察结构",
                no: "停止：输入不可用",
            },
            {
                id: "level-one-wave",
                question: "一级转向已按推进后回档确认？",
                detail: "上涨转换须先有更高高点，再确认其后的更高低点；下跌转换须先有更低低点，再确认其后的更低高点。不能用新推进之前的旧回档提前确认整段转向，相等不成立。未确认前仍更新整段最低或最高端点，已确认端点按当时可知时间发布；母子基础折线不变，二三级和全局策略消费同一正式一级结构。N 候选按独立基础折点形成，一级尚未转向不会单独取消 N 候选；依赖结构背景的买点继续使用此前已知背景。",
                source: "lecture_trend.py · _wave_reversals / reversal_trends",
                yes: "发布一级背景，继续独立 N 确认",
                no: "保持原一级方向，继续独立 N 确认",
                yesNext: "pivot",
                noNext: "pivot",
            },
            {
                id: "pivot",
                question: "确认点足以形成 N 结构？",
                detail: "按策略配置使用讲义因果、严格折线或日线代理确认点；至少三个点，且不能处于未解决的结构区间。",
                source: "integrated_strategy.py · pivot_history:101–150；generate_system_signals:205–225",
                yes: "检查 N 几何",
                no: "等待更多确认点",
            },
            {
                id: "n-geometry",
                question: "N 点次序、边界和窗口成立？",
                detail: "常规 N 的起点 A、颈线 B、回档 C 按时间排序且保持部分回撤。讲义因果外包 C 接纳等低创新高或等高创新低；两侧完全相等不算外包。C 在自身收盘确认，分步转折时实体须朝攻击方向；B 与 C 可在同一收盘才确认。C 转折后的攻击极值不冒充旧颈线，中间其他棒仍检查。阳母同日 A/B 与全局 V3 正 N 的阴母 A < B = C 保留独立严格外包条件；阴母须收阴且先高后低，等高、等低和十字星不放宽该分支。默认严格 N 条件保持。内包阴子另用独立 A < B = C 分支，只消费已有确认折线；母线非十字，阴子与前母线至少一侧严格内缩，用子线自己的颈线完成首次实虚攻击，再检查底部首个 N 资格，不以母线旧高替代子线颈线。超过结构窗口的结构跳过。",
                source: "n_shape.py · NSetup / observe_n；integrated_strategy.py · generate_system_signals",
                yes: "检查首次实虚攻击",
                no: "跳过该结构",
            },
            {
                id: "n-attack",
                question: "出现当时可确认的首次实虚攻击？",
                detail: "正 N 同棒收盘严格越过 B 收盘且最高严格越过 B 最高；倒 N 对称。讲义外包 C 当天须收盘严格越过 B 两层且前收盘未越过 B 收盘，才可同棒完成。C 只有影线越过颈线极值、收盘尚未越过极值时保持形成中；C 后第一棒仍须从前收盘重新严格攻击并同棒满足实过、虚过，不能把 C 的影线误当成已有完成。后续收盘无需另加越过 B 极值的门槛。持续站上、相等触及、跨棒拼接或未来才确认的锚点均不能补认。完成后冻结实际攻击棒的箱体锚点与防守。",
                source: "n_shape.py · observe_n；price_action.py · observe_attack",
                yes: "冻结攻击与防守位",
                no: "等待新攻击或跳过失效结构",
            },
            {
                id: "bottom-n-target-source",
                question: "这是底部启动或轧空低失效后的独立重算正 N？",
                detail: "一饱、二吐、五顶、十满共用 Core 发布的底部启动资格。使用当时已确认一级下降段的高点及其后到确认日的最低价，只有从该段最低点形成的首个正 N 冻结原箱。短历史尚无一级端点时，只能使用此前已确认的首个基础高点作为初始下跌依据；没有下跌证据不测算。相等低点保留较早底部；后续续涨、回调局部 N 和跨过已有启动 N 的更大结构不重开目标。新一级下跌确认或原底部严格破位时按可知日结束原目标；原 N 内部后来确认的高点不追溯终止原箱。普通 N 结构与入场识别仍保留，入场、转浪、目标退出和图表使用同一测幅来源，图表不自行补造四档目标。冻结轧空低被最低价严格跌破也立即失效，相等仍有效；当前图不画失效 N 和目标。守住起点时，以实际波段高点与新回调低首次实虚突破创建独立重算 N，同日多个来源不按日期或价格去重，各自测幅；买点通过来源 ID 绑定原组目标，日线候选仍择一。",
                source: "bottom_n_targets.py · bottom_n_target_history；positive_n_reformation.py · positive_n_reformations；integrated_strategy.py · generate_system_signals",
                yes: "冻结本组独立测幅，失效后重新确认",
                no: "仅识别结构，沿用已有底部 N 或等待新底部",
                yesNext: "direction",
                noNext: "direction",
            },
            {
                id: "direction",
                question: "这是可参与做多的正 N？",
                detail: "倒 N 进入风险退出路径，不参与买入。一个攻击只发出一次常规入场；独立的盘整与 C 波证据可另行确认。",
                source: "integrated_strategy.py · generate_system_signals:550–592",
                yes: "检查盘态",
                no: "倒 N：退出或等待新正 N",
            },
            {
                id: "regime",
                question: "形成多头 / 强多头轧空盘态？",
                detail: "常规 V1、V2、V3 买点要求已确认的轧空盘态。V3 局部正 N 的空头抵抗只计入突破当天或第二个交易日；之后的低开、高开收阴或长上影仍保留为原始 K 线证据，但不延长该 N 的抵抗。最早从突破日起第三根 K 线确认；已有窗口抵抗且原 N 防守从未失守时，确认日须为中大阳且短上影：实体/开盘至少 3%、实体/振幅至少 60%、上影/振幅最多 20%；收盘高于前收，且收盘与最高价分别严格高于原正 N 突破棒的收盘与最高价，可确认普通轧空。任一价格比较相等不能走原突破棒确认分支；盘中跌破滚动低点仍须保持原 N 防守完整，原防守失守后不恢复资格。原有收盘严格突破本轮前高的抵抗失败证据独立保留。上方二级压力及其他风险仍按各自门禁判断。回档续攻、盘整缺口和 C 波续攻按各自证据恢复到多头盘态；浅回撤横盘突破另走独立待选通道。",
                source: "market_regime.py · observe_market_regime；candle_strength.py；integrated_strategy.py · generate_system_signals",
                yes: "交给买点分类",
                no: "候选拒绝：not_squeeze_regime",
            },
        ],
    },
    {
        id: "entry",
        label: "② 买点与公共门禁",
        description:
            "常规 V3 买点路径；独立买点另见“浅回撤待选突破”和“组合 A 回调放量突破”通道。V1/V2 和 V3 幅度变体的差异在下方方案说明中列明。",
        mode: "gates",
        completion: "生成 LONG 信号，交给执行价、仓位与成交门禁",
        gates: [
            {
                id: "ten-full-pause",
                question: "此前十满到位后的买入限制已解除？",
                detail: "十满到达当日先暂停所有 V3 新买入与加仓，包括浅回撤横盘突破。A 段取原正 N 起点到十满当日高点；随后 B 段最低价从高点回撤至少 2/3 可在下一交易日起解除，不要求时间。若 B 段最低收盘只达到半幅，则从高点到 B 最低价的交易日间隔必须严格长于 A 段上涨间隔。23 个交易日内严格突破十满高点也可在下一交易日起解除；逾期创新高不能代替回撤条件。",
                source: "ten_full_entry.py · ten_full_entry_history；integrated_strategy.py · generate_system_signals",
                yes: "检查买点分类",
                no: "拒绝：wave_ten_full_pullback_pending",
                yesNext: "first-buy",
            },
            {
                id: "first-buy",
                question: "第一类资格成立？",
                detail: "攻击时翻多尚未成熟，二/三级已确认交替的低点不低于翻多起点，之后有新正 N。幅度变体另要求交替低点或冻结窗口最低收盘的深回撤严格大于设定比例。",
                source: "whole_wave_entry.py · select_wave_entry:40–83；strategy_profiles.py · WAVE_PROFILES",
                yes: "第一类 · transition_squeeze",
                no: "继续检查第二类资格",
                yesNext: "pressure",
                noNext: "second-buy",
            },
            {
                id: "second-buy",
                question: "第二类资格成立？",
                detail: "翻多成熟须在攻击前确认；之后先有新高，再有回档点，再有新正 N。以峰值到翻多起点为分母，峰值到已观察最低收盘的回撤须符合当前方案的 ≤1/3、≤1/2 或 <1/2。",
                source: "whole_wave_entry.py · select_wave_entry:84–107；strategy_profiles.py · WAVE_PROFILES",
                yes: "第二类 · mature_shallow_squeeze",
                no: "拒绝：无有效第一类或第二类上下文",
                yesNext: "pressure",
                row: 1,
            },
            {
                id: "pressure",
                question: "上方二级阻力已解决？",
                detail: "二级突破受阻后，至少隔一日由无新空抵的阳线收盘越过抵抗阶段全部前高，且守住原突破防守，才解除阻断；盘中跌破前根滚动低点但收盘创本轮新高可通过。同一次多级突破证据或完成 A/B 后的 C 波恢复也可解除。",
                source: "integrated_strategy.py · generate_system_signals:593–611",
                yes: "检查原 N 收盘",
                no: "拒绝：secondary_breakout_resistance_unresolved",
            },
            {
                id: "original-close",
                question: "确认收盘高于原 N 攻击收盘？",
                detail: "低于或等于原 N 攻击棒收盘的反弹不能复活旧 N。",
                source: "integrated_strategy.py · generate_system_signals:617–620",
                yes: "检查弱 N",
                no: "拒绝：squeeze_below_original_n_close",
            },
            {
                id: "weak-n",
                question: "弱 N 已由连续轧空或新证据修复？",
                detail: "弱攻击需要未破防守、放量收盘突破续攻位；盘整、C 波、多级突破、反转或独立重确认可提供替代证据。",
                source: "integrated_strategy.py · generate_system_signals:621–635",
                yes: "检查倒 N 后再入场",
                no: "拒绝：weak_n_requires_uninterrupted_squeeze",
            },
            {
                id: "inverse-reentry",
                question: "倒 N 后重入场阻断已解除？",
                detail: "若旧倒 N 阻断仍在，必须出现新强轧空、深回档恢复、C 波恢复或符合条件的缺口路径。深回档恢复仍要求整段回撤至少 2/3、结构归属与可知时序成立、回调低点未破且收盘严格收复杀多高；原正 N 突破棒的收盘与最高价严格双比较可提供该路径的轧空确认，独立风险门禁继续适用。",
                source: "integrated_strategy.py · generate_system_signals:665–683；inverse_reentry.py",
                yes: "检查确认日量能",
                no: "拒绝：倒 N 后重入场未获证据",
            },
            {
                id: "volume",
                question: "量能通过或 C 波价格突破豁免？",
                detail: "V3 确认日累计量严格大于前一日总量；C 波已验证的价格突破可作为替代。V1/V2 使用相对量能门槛。",
                source: "integrated_strategy.py · generate_system_signals:687–699；strategy_profiles.py",
                yes: "检查止损与目标",
                no: "拒绝：attack_volume_unavailable_or_low",
            },
            {
                id: "target",
                question: "防守位低于价格且有未命中目标？",
                detail: "目标取最近未命中的等幅、1P、2T 或有效波段投影，不可跳过近目标抬高盈亏比。C 波使用冻结的防守和等幅目标。",
                source: "integrated_strategy.py · generate_system_signals:701–718",
                yes: "检查策略盈亏比",
                no: "拒绝：no_live_structural_risk_reward",
            },
            {
                id: "preflight",
                question: "前置盈亏比已通过或关闭？",
                detail: "V1/V2 启用时，收盘价到最近目标的毛盈亏比需达到 1.5。V3 关闭此信号前置门禁，执行价格仍需通过净盈亏比门禁。",
                source: "integrated_strategy.py · generate_system_signals:719–727；strategy_profiles.py",
                yes: "V3 关闭，或 V1/V2 毛盈亏比 ≥1.5",
                no: "拒绝：insufficient_close_gross_reward_risk；不消耗 N",
            },
        ],
    },
    {
        id: "wave",
        label: "③ A/B → C 波续攻",
        description: "普通 A 与强 A 分路，所有锚点在当天攻击前冻结；强 A 实体确认后可由更高缺口再确认一次。",
        mode: "gates",
        completion: "C 波证据回到公共入场门禁，目标为 B + A 等幅",
        gates: [
            {
                id: "ab-known",
                question: "原 N 已轧空，且此前 A/B 可冻结？",
                detail: "合格正 N 严格突破一饱即独立确认 A，不等待 B/C、二级翻转或轧空；达到二吐升级强势 A，未结束的 A 高点可延伸。C 入场仍要求原 N 轧空、此前 A 顶及实际回落 B。强势 A 与普通 A 的 B 均可跌破轧空低；最低价严格跌破整段 A 起点即失效，相等仍有效，后续没有原组 C，等待新 A。旧 N 防守或目标退役不撤销已经成立的 A。当天高点不能反过来构造自己的 A/B。",
                source: "a_wave.py · a_wave_history；a_wave_rules.py · a_origin_broken；wave_continuation.py · wave_pullback_context",
                yes: "比较 A 与原 N 目标",
                no: "等待完整 A/B 或防守失效",
            },
            {
                id: "a-class",
                question: "A 达到原 N 的 2T？",
                detail: "A 高点 ≥ 二吐（2T）是强势 A；一饱（1P）< A 高点 < 二吐是普通 A。一饱必须严格突破，二吐的等号表示已达到。强 A 与普通 A 都保留完整 A 起点，内部正 N 不替换父 A。",
                source: "a_wave_rules.py · classify_a_attack；wave_continuation.py · wave_pullback_context",
                yes: "强 A：缺口或强实体放量",
                no: "普通 A：阳线收盘突破已知回档高点",
                noNext: "ordinary-trigger",
            },
            {
                id: "strong-trigger",
                question: "强 A 有缺口，或强实体且放量？",
                detail: "强实体需实体 ≥ 开盘价 3%，且实体 ≥ 全日振幅 60%；非缺口强实体还需高于前日成交量。同一 A/B 的实体确认只发一次，之后仅严格更高的缺口可升级确认一次。",
                source: "wave_continuation.py · wave_gap_entry / wave_confirmation_is_new",
                yes: "检查突破证据",
                no: "强 A 暂不续攻；继续观察",
                yesNext: "defense-target",
            },
            {
                id: "ordinary-trigger",
                question: "普通 A：阳线收盘突破已知回档高点？",
                detail: "普通 A 至少触达 1P、未到 2T；B 可破轧空低，但最低价须守住 A 起点。当前棒须为阳线，且收盘高于 A 后已确认的回档高点。",
                source: "wave_continuation.py · wave_pullback_context:20–45；wave_gap_entry:112–126",
                yes: "普通 A 回升通道",
                no: "普通 A 等待收盘突破",
                yesNext: "defense-target",
                row: 1,
            },
            {
                id: "defense-target",
                question: "防守仍在，且价格低于 B+A 等幅？",
                detail: "当天低点不得失守原防守；已达到等幅目标则不再追入。非缺口棒若刷新 B，使用当前已观察低点重算目标。",
                source: "wave_continuation.py · wave_gap_entry:89–111",
                yes: "检查阻力与收盘",
                no: "失守防守或目标已达：不入场",
            },
            {
                id: "known-high",
                question: "对应的回升 / 突破证据成立？",
                detail: "阻力高点如被使用，必须位于 A 之后、今天之前，且已在今天之前确认。普通 A 必须阳线收盘站上；强 A 可走缺口价格突破、放量缺口或放量强实体收盘突破。",
                source: "wave_continuation.py · wave_gap_entry:112–126",
                yes: "形成 C 波价格 / 量能证据",
                no: "对应突破不成立：继续观察",
            },
        ],
    },
    {
        id: "execution",
        label: "④ 执行与成交",
        description: "LONG 信号通过后才进入模拟执行；任一拒单都不能显示为 B 成交。",
        mode: "gates",
        completion: "记录 BUY 成交、持仓和成本证据",
        gates: [
            {
                id: "execution-time",
                question: "信号仍有效，执行时点已到？",
                detail: "V3 常规买点按当天收盘模拟，盘整与 C 波可在已完成的 5 分钟证据后入场；C 波分钟请求先用昨日已知且仍存活的攻击时交替或同一 N 联合确认预筛选，旧结构仅守住价格防守位不能反复请求分钟。实际确认仍重放已完成分钟前缀，不借今日最终行情。待执行信号超出 TTL 则到期，不补造历史成交。",
                source: "backtest.py · run_backtest:349–378, 546–598；intraday_entry.py · resolve_consolidation_entries；whole_wave_entry.py · wave_entry_contexts；strategy_profiles.py · whole_wave_profile execution",
                yes: "取得实际执行价格",
                no: "到期或未确认：不成交",
            },
            {
                id: "position-slot",
                question: "新开仓有槽位，或已有持仓允许加仓？",
                detail: "新开仓受最大持仓数量限制。V3 已有该股持仓、无待执行退出且当日未卖出时，可继续处理独立合格买点；其他方案保留原有持仓拒单规则。",
                source: "backtest.py · execute_entry；strategy_profiles.py · whole_wave_profile",
                yes: "检查可买状态",
                no: "取消：position_limit / already_held / exit_pending",
            },
            {
                id: "buyable",
                question: "该时点可买入？",
                detail: "普通不可买或一字涨停拒单；V3 已观察到非一字涨停可按所选模型模拟成交，并明确标记未验证排队成交的假设。",
                source: "backtest.py · execute_entry:256–274；strategy_profiles.py · daily_limit_fill",
                yes: "检查执行价与防守",
                no: "取消：not_buyable / not_buyable_at_close",
            },
            {
                id: "price",
                question: "执行价高于失效位且跳空未超限？",
                detail: "实际执行价不得触及或低于信号失效位；相对信号参考价的跳空不得超过 max_entry_gap。",
                source: "backtest.py · execute_entry:273–278",
                yes: "检查目标是否仍有效",
                no: "取消：invalidated / entry_gap",
            },
            {
                id: "live-target",
                question: "最近目标仍高于实际执行价？",
                detail: "若目标已被开盘或收盘执行价耗尽，不把信号当成交。",
                source: "backtest.py · execute_entry:279–292",
                yes: "按四项上限计算股数",
                no: "取消：target_exhausted",
            },
            {
                id: "sizing",
                question: "仓位、风险、流动性、现金足够一手？",
                detail: "数量取仓位权重、风险预算、当日剩余流动性、现金四个上限的最小值，再按复权整手向下取整。加仓先扣除原持仓占用的仓位和止损风险，含手续费复核成交后上限并合并成本；任一余额不足一手则取消。",
                source: "backtest.py · execute_entry",
                yes: "检查净盈亏比",
                no: "取消：限制项低于一手 / 费用后现金不足",
            },
            {
                id: "net-rr",
                question: "启用时，执行价净盈亏比达到门槛？",
                detail: "以实际执行价、滑点、买卖费用和确定的股数计算净收益/净风险；启用过滤且低于信号要求时拒单，V3 默认要求 1.5。",
                source: "backtest.py · execute_entry:316–325；strategy_profiles.py · primary_filters",
                yes: "模拟 BUY 成交",
                no: "取消：insufficient_net_reward_risk",
            },
        ],
    },
    {
        id: "exit",
        label: "⑤ 风险退出与减仓",
        description: "先检查整仓风险退出，再考虑分段减仓；无触发时继续持有并观察下一根 K 线。",
        mode: "exits",
        completion: "无退出证据：持仓延续至下一交易日",
        gates: [
            {
                id: "structure-exit",
                question: "结构未解、倒 N、空头转向或前上升低点被收盘跌破？",
                detail: "系统信号先于同日新入场判断；触发 EXIT 后该日不再生成 LONG。",
                source: "integrated_strategy.py · generate_system_signals:550–573",
                yes: "EXIT 风险信号；停止当日入场",
                no: "检查二饱后实体反包",
            },
            {
                id: "two-t-body-clear",
                question: "二饱到位后，阴线实体反包且量超过最近阴线？",
                detail: "有效正 N 必须在此前交易日已到二饱（二吐/2T）。后续任一交易日收阴，开盘 ≥ 前阳线收盘、收盘 ≤ 前阳线开盘且至少一端严格越过，成交量严格大于此前最近阴线的正成交量即全清；十字线不作阴线量基准。不要求覆盖影线、5% 实体或超过前日成交量，不依赖先前减仓。已失效或未来目标不能触发。整仓退出优先于减仓，并取消同日新买与加仓；T+1 或不可卖时保留待卖执行。",
                source: "two_t_resistance.py · two_t_resistance_history；backtest.py · run_portfolio",
                yes: "当日模拟收盘清空余仓",
                no: "检查五顶后低开长上影",
            },
            {
                id: "five-top-gap-upper-shadow-clear",
                question: "五顶或十满到位后，实体母子长上影或低开收低长上影？",
                detail: "有效正 N 必须在此前交易日已达到五顶或十满。独立实体母子路径：今日开收实体区间被昨日开收实体区间包含，至少一侧严格包含，允许一侧相等及今日十字实体；实体判断不使用最高最低，今日最高可以高于昨日最高。子线长上影占正振幅至少 50% 即100%清仓，不要求低开、收阴或放量，两个实体完全相等不算母子。保留此前低开路径：当前开盘 < 前收、收盘 ≤ 开盘（包含十字线），上影为最高价减去开收较高值，须占正振幅至少 50%，相等允许。无需放量或此前减仓；当日达到、未来或已失效目标不能触发。同时触发既有全清时沿用原退出原因及对应目标证据。完整同源分钟数据以已完成五分钟线的累计日内 OHLC 判定，下一根五分钟线开盘按当刻已观察到的交易权限模拟卖出；模型启用且已观察到跌停打开时，下一棒跌停开盘也按零滑点模拟，未验证排队，不使用当日日线未来高低。缺少完整分钟时显式回退日线收盘，已启用非一字限价收盘模型且来源证明曾在跌停价以上成交时，非一字跌停按原始收盘价、零滑点模拟，未验证排队；不要求普通收盘可卖标志为真，一字跌停不放行。日线统一收盘动作中整仓退出优先于减仓；分钟退出确认后阻止当日后续新买与加仓，确认前已发生的交易及费用保留。T+1 或当刻不可卖时保留待卖执行。",
                source: "wave_exhaustion_exit.py · observe_five_top_body_upper_shadow_clear / observe_five_top_upper_shadow_clear；intraday_wave_exit.py · observe_intraday_five_top_exit；backtest.py · run_portfolio；data.py · close_sell_permissions",
                yes: "按 100% 退出目标进入分钟或日线回退撮合",
                no: "检查 V3 其他整仓风险",
            },
            {
                id: "hard-risk",
                question: "放量倒 N、巨量反包、五顶后低开放量破前开或其他波段风险？",
                detail: "V3 巨量高开强阴反包、放量倒 N、波段异常与趋势翻空可整仓退出。已知正 N 在此前交易日达到五顶或十满，随后若低开、收盘低于前日开盘且量大于此前最近阴线，当日收盘清仓；原有阴线跌破昨低昨收及前天子低的放量清仓仍有效。强 A 的 C 浪首次接近等浪目标一分钱内遇空头抵抗后，后续首次低点与收盘双破昨日且量大于此前最近阴线时也生成清仓信号；有持仓时当日收盘清空余仓。正 N 上攻巨量阴线压力区遇不利 K 通常全清；未回补跳空且收高时先减半，成交后首次收跌清余仓。持仓大幅上涨后盘中突破阴线压力高点并遇空头抵抗，后续首次不利 K 清仓。盘中突破至少 20 个交易日前的近 120 日未受空头抵抗阳线最高价，遇空头抵抗且收盘未站稳并出现不利 K 时先减半，成交后首次收低清余仓。",
                source: "strategy_profiles.py · whole_wave_profile definition；wave_exhaustion_exit.py；trend_flip_exit.py；pressure_exit.py",
                yes: "按对应风险全清或减仓",
                no: "检查二级 C 浪抵抗失败",
            },
            {
                id: "secondary-c-exit",
                question: "已知二级 A/B/C 等幅目标到位后，双长影次日收低破位？",
                detail: "已确认二级低点与来源 A 高、B 低先于突破可知；盘中越过 A 高后连续两日空头抵抗，下一日触及等幅目标且上下影各占振幅至少 30%，再下一日阴线收盘跌破长影 K 线低点与 A 高，才按收盘清空余仓。",
                source: "trend_flip_exit.py · _secondary_wave_exhaustion_history；strategy_profiles.py · secondary_c_wave_reversal_exit",
                yes: "当日收盘清空余仓",
                no: "检查防守与目标状态",
            },
            {
                id: "target-not-exit",
                question: "只是达到 1P / 2T / 等幅 / 延伸目标？",
                detail: "V3 测量目标是观察里程碑，不自动生成目标卖单。V1/V2 保留各自封存的目标退出规则。",
                source: "strategy_profiles.py · whole_wave_profile:42–118",
                yes: "记录目标并继续观察退出证据",
                no: "检查分段减仓",
            },
            {
                id: "staged",
                question: "已验证分钟窗口跌破 35% / 65% 位或弱反弹？",
                detail: "V3 分段减仓由已完成的 5 分钟窗口触发，下一时间片撮合；更高优先级整仓风险先执行。分钟数据缺失时显式标记日线回退。",
                source: "staged_exit.py；strategy_profiles.py · whole_wave_profile execution",
                yes: "按阶段减仓 / 剩余仓位清退",
                no: "检查小 N 与放量下跌",
            },
            {
                id: "partial",
                question: "压力区未补跳空、小 N、放量下跌、C 浪空头抵抗或减仓后倒 N 触发？",
                detail: "压力区不利 K 若跳空未回补且收高，先卖出当前持仓 50%；小 N 可累计减仓 30%，放量下跌累计 70%，普通 A 的 C 浪异常累计 80%。已知强 A 的 C 浪等浪目标首次接近一分钱内且出现空头抵抗 K 线时，不要求当日放量，按配置的累计目标减仓（默认 80%）。减仓后倒 N 可累计减仓 90%。各比例受已有卖出和整仓优先级约束。",
                source: "strategy_profiles.py · whole_wave_profile definition；integrated_strategy.py",
                yes: "记录对应累计减仓目标",
                no: "继续持仓",
            },
        ],
    },
    {
        id: "nested-breakout",
        label: "二级后一级交替突破",
        description: "V3 新增买入通道：两级交替低点已依次确认，放量阳线突破时可由当日正 N 完成入场确认。",
        mode: "gates",
        completion: "生成一次 LONG，进入原有执行与成交门禁",
        gates: [
            {
                id: "nested-lows",
                question: "先二级、后一级交替低点在前日已确认且有效？",
                detail: "发生日期与确认日期分别严格先后；一级正 N 须对应其整段起点及交替低点，期间不得跌破任一级交替低点。",
                source: "nested_alternation_breakout.py；chart_entry_history.py",
                yes: "检查当日量价突破",
                no: "等待两级低点确认或重建结构",
            },
            {
                id: "nested-volume-price",
                question: "阳线放量收盘突破一级翻多高及全部整理高？",
                detail: "成交量严格大于前日正成交量，收阳且收盘严格突破此前最高价；有明显长上影抵抗时不触发，不要求开盘跳空。",
                source: "nested_alternation_breakout.py · nested_alternation_breakout",
                yes: "检查其他风险与测幅目标",
                no: "不生成该通道买点",
            },
            {
                id: "nested-risk",
                question: "倒 N、其他压力、整仓风险及最近目标检查通过？",
                detail: "当日正 N 可以确认买点；沿用其原防守和最近未达到目标。两低组合只生成一次买入信号，成交仍按费用、仓位、流动性及涨停设置处理。",
                source: "integrated_strategy.py · generate_system_signals；backtest.py",
                yes: "二级后一级交替突破 LONG",
                no: "保留拒绝原因，等待后续有效信号",
            },
        ],
    },
    {
        id: "combined-a-breakout",
        label: "组合 A 回调放量突破",
        description: "V3 全局独立入场通道：组合 A 顶后回调及整理达到时间条件、收盘守住 2/3，再由放量中大阳线严格突破。",
        mode: "gates",
        completion: "组合 A 突破生成一次 LONG，进入原有风险、执行与成交门禁",
        gates: [
            {
                id: "combined-a-known",
                question: "组合 A 与同源结构在当日之前已确认？",
                detail: "冻结组合 A 起点、C 顶和确认可知日，按发生日期与可知日期核对已有回调及整理；未知或失效组合不能借后续数据生成历史买点。",
                source: "combined_a_entry.py · combined_a_contexts_from_geometry；chart_entry_history.py",
                yes: "检查顶后回调及整理时间",
                no: "等待有效组合确认",
            },
            {
                id: "combined-a-time",
                question: "回调及整理时间超过组合内部回调或子级回调？",
                detail: "从组合 A 的 C 顶到突破日计算交易日间隔，包含底部整理；须严格长于组合内部回调或最末已确认同源子级回调，满足其一。未提供的子级时长不能替换为零，相等不通过。",
                source: "combined_a_entry.py · combined_a_entry_history",
                yes: "检查回调期收盘防守",
                no: "继续等待足够的回调时间",
            },
            {
                id: "combined-a-close",
                question: "回调期间全部收盘守住 2/3 回撤价？",
                detail: "2/3 回撤价为组合顶减去整段涨幅的 2/3；最低收盘须大于或等于该线，相等允许。仅盘中低点短暂越线不算收盘失守；任何已知收盘跌破后，不因重新收复恢复旧组合入场资格。",
                source: "combined_a_entry.py · combined_a_entry_history",
                yes: "检查放量中大阳线突破",
                no: "组合收盘失守：不产生该买点",
            },
            {
                id: "combined-a-trigger",
                question: "放量中大阳线收盘严格突破已知回调参考高？",
                detail: "参考高在触发日前发生且已可知，收盘须首次从下方严格突破；或未回补的跳空同时收盘越过前日最高价。收盘相等或仅盘中越线不触发。两条突破分支都须阳线实体至少为开盘价 3%、占全天振幅至少 60%，成交量严格大于前日正成交量。",
                source: "combined_a_entry.py · combined_a_entry_history",
                yes: "检查全局风险和组合顶目标",
                no: "继续观察量价与突破证据",
            },
            {
                id: "combined-a-risk",
                question: "倒 N 观望、目标限制与原有成交门禁通过？",
                detail: "以回调期最低价为防守，以尚未到达的组合 A 顶为目标；同一组合只确认一次。仍受倒 N 观望、目标阶段禁买、费用后盈亏比、仓位、流动性与涨停成交设置约束，LONG 不保证 BUY 成交。",
                source: "integrated_strategy.py · generate_system_signals；backtest.py",
                yes: "组合 A 回调放量突破 LONG",
                no: "保留拒绝原因，不补造买入成交",
            },
        ],
    },
    {
        id: "shallow-base",
        label: "浅回撤待选突破",
        description:
            "V3 独立买入通道，默认开启、可关闭。0.618 至 2/3 的低点先作为空多交替待选，不擅自升级为正式二/三级低点。",
        mode: "gates",
        completion: "只在突破确认日生成一次 LONG；仍须通过执行与成交门禁",
        gates: [
            {
                id: "shallow-enabled",
                question: "V3 浅回撤横盘突破开关已开启？",
                detail: "默认开启；关闭后该通道不生成待选证据或买点，常规 V3 信号不受影响。",
                source: "integrated_strategy.py · SystemStrategy.shallow_base_breakout_enabled；visualization.py · tdx_backtest",
                yes: "核对冻结的结构锚点",
                no: "通道关闭：不产生特殊买点",
            },
            {
                id: "shallow-candidate",
                question: "确认低点回撤达到 0.618、但不足 2/3？",
                detail: "使用当时可知的正式二/三级起点与高点，以及已确认的一级来源低点；回撤 0.618 ≤ 深度 < 2/3，且没有跌破原起点。只记待选，不改变正式趋势线。",
                source: "shallow_base_breakout.py · shallow_candidate_from_geometry；chart_entry_history.py",
                yes: "观察低点之后的横盘",
                no: "等待其他结构或普通买点",
            },
            {
                id: "shallow-base-range",
                question: "守低横盘至少 40 根、最多 120 根 K 线？",
                detail: "从待选低点到突破日经历 40–120 个交易日，期间不得跌破待选低点；最近 40 根 K 线的最高至最低振幅不超过 18%。",
                source: "shallow_base_breakout.py · shallow_base_history",
                yes: "检查阳线与量价突破",
                no: "继续等待或候选失效",
            },
            {
                id: "shallow-breakout",
                question: "放量大阳线收盘突破整段横盘前高？",
                detail: "阳线实体至少为开盘价 5%、占全天振幅至少 60%，收盘落在全天振幅上部 20%；量为此前 20 日均量至少 2 倍且大于前日，收盘超过待选低点之后全部已知 K 线的最高价。",
                source: "shallow_base_breakout.py · shallow_base_history",
                yes: "检查最近正式高点的空间",
                no: "不生成特殊买点",
            },
            {
                id: "shallow-risk",
                question: "以横盘低点防守、最近正式高点为目标，毛盈亏比至少 1.5？",
                detail: "突破日收盘必须高于最近 40 根 K 线最低价、低于此前冻结的正式波段高点；按该防守和最近目标计算毛盈亏比，低于策略门槛则放弃。",
                source: "shallow_base_breakout.py · shallow_base_history；integrated_strategy.py · generate_system_signals",
                yes: "浅回撤横盘突破 LONG",
                no: "空间不足：不追入",
            },
        ],
    },
] as const;

export const topologyProfileNotes = [
    "C 浪目标标识固定在对应 B 低点日期上方，0.618、等浪与已可知 1.618 共用该显示锚点；悬停、选择和平移不会将其移到其他日期。B 离开图窗时隐藏，移回后恢复原位置。目标价格、可知日和首次触及证据保持原规则。",
    "V3 v102：合格正 N 严格突破一饱立即确认 A，达到二吐升级强势；A 高点可延伸，确认不等待 B/C 或正式二级翻转。A 成立后仅按原点最低价严格破位永久失效，原组不再产生后续 C；旧 N 轧空低失效或目标退役不取消已经成立的 A。独立 N 重算和目标来源规则继续保留，C 观察不直接生成买单。",
    "二、三级趋势线在市场最高价严格突破已知同级前高、或最低价严格跌破已知同级前低时立即确认并画实线。首次突破日冻结，末端继续延伸；没有新同级突破时，反向虚线须等极值之前冻结的下一级末升低或末跌高严格破位，确认整段趋势扭转；局部两高、两低反向不算扭转，相等、未知与跨路径不启用。不能把关键位滚动到回调点，实际破位前不画反向线；方向确认与正式反转端点分开，不提前冻结突破棒或替换策略输入。",
    "V3 v98 一级趋势有序确认：先创新高再确认其后更高低点，或先创新低再确认其后更低高点；禁止用推进前旧回档提前冻结整段端点。确认前持续跟踪整段极值，基础母子折线约定保持，各级趋势与策略使用同一因果结构。",
    "V3 v96 五顶后低开长上影全清：此前有效正 N 已到五顶或十满，开盘 < 前收、收盘 ≤ 开盘（含十字线）、上影占振幅 ≥ 50% 即按 100% 退出目标清空余仓，无需放量或此前减仓。完整分钟以已完成五分钟线累计行情判定并在下一根开盘模拟；启用既有非一字限价模型且判定时已观察到跌停打开，可按下一棒跌停开盘原价、零滑点模拟。缺分钟显式日线收盘回退，模型允许非一字跌停按原始收盘价、零滑点卖出；两种假设都未验证排队。原有入场通道与 V1/V2 封存定义保持各自口径。",
    "V3 组合 A 回调放量突破：C 顶后回调及整理时间严格超过组合内部回调或最末同源子级回调，收盘守住 2/3，放量中大阳线收盘严格突破此前已知回调高点；不要求跳空，沿用全局风控与成交门禁。",
    "V3 新增二级后一级交替低点放量突破：两级低点在前日已依次确认且有效，放量阳线收盘突破一级翻多高及整理高，当日正 N 完成即可确认买点；沿用原防守、测幅与成交检查。",
    "V3 默认：第一类为二/三级确认交替后新正 N；第二类浅回撤 ≤1/3。确认日量能严格大于前日；信号阶段不做毛盈亏比前置筛选。",
    "V3 幅度方案：第一类可要求 >2/3 或 >1/2，第二类可选 ≤1/3、≤1/2 或最低收盘价 <1/2；具体边界由 WAVE_PROFILES 决定。",
    "V3 独立浅回撤横盘突破默认开启、可关闭：0.618 ≤ 回撤 < 2/3 的一级来源低点先记为交替待选，守低窄幅横盘至少 40 根 K 线后，放量大阳线收盘突破整段横盘前高并满足风险收益门槛才生成买点。",
    "V2：分级双买点的旧定义；V1：讲义因果轧空定义；严格折线与日线代理是研究对照，不能把代理结果解释为 V3 因果证据。",
    "信号、执行和成交是不同层：拓扑中的 LONG 只代表候选通过。成本、风险预算、可用现金、整手与涨停撮合仍可能拒单。",
    "持仓每次归零结束一轮，再次买入独立计算成本 MAE；最终最大回撤取完整轮次中最深的亏损。减仓不重置，加仓只更新当时成本，未清仓只展示本轮亏损。",
] as const;

/** 策略源码指纹；策略或证据逻辑变更时，复核路径后在此更新。 */
export const strategySourceDigest = "be7fdf3776ba492cd6a0ce0668856cb1bf50cb9136130d288068a241999ff360";
